openapi: 3.0.0
info:
  title: InvestCo Wealth Management
  description: Minimum Viable Product for InvestCo Wealth and Asset Management

externalDocs:
  description: Checkout the GitHub repo
  url: https://github.com/Ukhu/invest-co-wealth-management

servers:
- url: /api/v1
  description: Host

tags:

security:
- ApiKeyAuth: []

paths:
  
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
